"""
Executor component.

The Executor is responsible for executing
an investigation plan generated by the Planner.
"""

from centaurus.executor.execution import ExecutionPlan
from centaurus.plugin_manager.plugin_manager import PluginManager

class Executor:
    """
    Executor component.

    ```
    The Executor coordinates the execution of the tasks contained
    in an ExecutionPlan.

    It delegates plugin execution to the Plugin Manager.

    The Executor never:
    - creates execution plans;
    - modifies execution plans;
    - replans investigations;
    - discovers or loads plugins directly.
    """

    def __init__(self, plugin_manager: PluginManager) -> None:
        """
        Create a new Executor.

        The Plugin Manager is provided by the Core, which owns
        the lifecycle of the framework components.
        """

        self._plugin_manager = plugin_manager

# ==========================================================
# Public interface
# ==========================================================

    def execute(self, plan: ExecutionPlan) -> None:
        """
        Execute all tasks contained in an execution plan.
        """

        for task in plan.tasks:
            self._plugin_manager.execute(task)

