"""
Executor component.

The Executor is responsible for executing
an investigation plan generated by the Planner.
"""

from centaurus.executor.execution.execution_plan import ExecutionPlan
from centaurus.plugin_manager.plugin_manager import PluginManager


class Executor:
    """
    Executor component.

    The Executor coordinates the execution of the tasks contained
    in an ExecutionPlan.

    It never creates, modifies or replans investigations.
    """

    # ==========================================================
    # Public interface
    # ==========================================================

    def execute(self, plan: ExecutionPlan) -> None:
        """
        Execute an investigation plan.
        """

        manager = PluginManager()

        for task in plan.tasks:
            manager.execute(task)

    