"""
Executor component.

The Executor is responsible for executing
an investigation plan generated by the Planner.
"""

from centaurus.executor.execution import (
    ExecutionFailure,
    ExecutionPlan,
)
from centaurus.exceptions import PluginExecutionError
from centaurus.plugin_manager.plugin_manager import PluginManager


class Executor:
    """
    Executor component.

    The Executor coordinates the execution of the tasks contained
    in an ExecutionPlan.

    It delegates plugin execution to the Plugin Manager.

    The Executor never:
    - creates execution plans;
    - modifies execution plans;
    - replans investigations;
    - discovers or loads plugins directly.
    """

    def __init__(
        self,
        plugin_manager: PluginManager,
    ) -> None:
        """
        Create a new Executor.

        The Plugin Manager is provided by the Core, which owns
        the lifecycle of the framework components.
        """

        self._plugin_manager = plugin_manager

    # ==========================================================
    # Public interface
    # ==========================================================

    def execute(
        self,
        plan: ExecutionPlan,
    ) -> dict:
        """
        Execute all tasks contained in an execution plan.

        Isolated plugin failures are recorded and later planned tasks
        continue to execute sequentially. Framework failures outside
        the plugin boundary still propagate.

        Returns a structured execution result.
        """

        results = []
        failures: list[ExecutionFailure] = []

        for task_index, task in enumerate(
            plan.tasks,
            start=1,
        ):
            try:
                result = self._plugin_manager.execute(
                    task,
                )
            except PluginExecutionError as exc:
                failures.append(
                    ExecutionFailure.from_exception(
                        task_index=task_index,
                        task=task,
                        exc=exc,
                    )
                )
                continue

            results.append(result)

        if failures and results:
            status = "partial"
        elif failures:
            status = "failed"
        else:
            status = "completed"

        return {
            "status": status,
            "results": results,
            "failures": failures,
        }